Fix missing-prototypes
thunarx-python-object.c:70:5: error: no previous prototype for '__PyString_Check' [-Werror=missing-prototypes]
thunarx-python-object.c:78:7: error: no previous prototype for '__PyString_AsString' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>